### PR TITLE
chore: bumping jellyfish version to 1.1.0

### PR DESCRIPTION
**Pull request by nick-redfearn**
This morning I was trying to understand how to contribute and I spotted that the latest version of the jellyfish package is not being used. So, I've bumped it to 1.1.0 as an excuse to learn about how to contribute.

Jellyfish changelog -> https://github.com/jamesturk/jellyfish/blob/main/docs/changelog.md

### CODE REVIEW

**Review by nehanene15 — APPROVED** [review]
Thanks for contributing! LGTM. 
Feel free to look through issues tagged 'good first issue' for more ways to contribute as well!

**Comment by nick-redfearn** [comment]
Thanks @nehanene15 - OK to merge?

**Comment by nehanene15** [comment]
> Thanks @nehanene15 - OK to merge?

Yes, go for it! We use squash and merge & usually let the PR author press the button :)

**Comment by nick-redfearn** [comment]
@nehanene15 For some reason I dont seem to have the button 🤷 
image

**Comment by nehanene15** [comment]
> @nehanene15 For some reason I dont seem to have the button 🤷 

My bad - I think you would need elevated permissions on the repo for that. I went ahead and merged!

**Pull request merged**
