### PR TITLE
feat: Addition of log level as an argument for DVT logging and replac…

### PR DESCRIPTION
**Pull request by kanhaPrayas**
This PR has the following updates:

- log-level as an option in arguments
- Replacing print statements with logging.info
- Changing log-level from info to debug in combiner.py

### CODE REVIEW

**Review by nehanene15 — CHANGES_REQUESTED** [review]
Can we update the README with the flag? Otherwise LGTM

**Comment by kanhaPrayas** [comment]
> Can we update the README with the flag? Otherwise LGTM

Updated the ReadME

**Review by nehanene15 — APPROVED** [review]
LGTM.
Small nit: We should update the README for running configs [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/README.md?plain=1#L339) to this: 
```
data-validation (--verbose or -v) (--log-level or -ll) configs run -c citibike.yaml
```

**Comment by kanhaPrayas** [comment]
> LGTM. Small nit: We should update the README for running configs [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/README.md?plain=1#L339) to this:
> 
> ```
> data-validation (--verbose or -v) (--log-level or -ll) configs run -c citibike.yaml
> ```

Done

**Pull request merged**
