### PR TITLE
chore: Create SECURITY.md

### LINKED ISSUE #1348: Add Security Policy file to the repository
According to the insights checklist: https://github.com/GoogleCloudPlatform/professional-services-data-validator/community

### PR DESCRIPTION
**Pull request by helensilva14**
Closes #1348 

Got the same file available on https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/SECURITY.md

### CODE REVIEW

**Comment by nj1973** [comment]
I switched the file to have Google recommended content. I expect both versions are acceptable, see what you think.

**Comment by helensilva14** [comment]
> I switched the file to have Google recommended content. I expect both versions are acceptable, see what you think.

No problem, thank you!

**Comment by helensilva14** [comment]
I can't approve my own PR so that will be the last thing left, after build pass

/gcbrun

**Review by nj1973 — APPROVED** [review]
LGTM

**Pull request merged**
