### PR TITLE
fix: Oracle INTERVAL exception in validate schema

### LINKED ISSUE #1211: Oracle exception validating table with INTERVAL DAY TO SECOND column
Example validate schema command on table with INTERVAL DAY TO SECOND column, we tried to exclude the column to make the command pass but still get the exception:
```
data-validation validate schema --source-conn ora --target-conn pg \
--tables-list owner.t1 \
--exclusion-columns col_interval
...
Traceback (most recent call last):
  File "C:\Users\u\DVT\lib\site-packages\multipledispatch\dispatcher.py", line 269, in __call_:
    func = self._cache[types]
KeyError: (<class 'sqlalchemy.dialects.oracle.cx_oracle.OracleDialect_cx_oracle'>, <class 'sqlalchemy.dialects.oracle.base.INTERVAL'>)
...
  raise NotImplementedError(
NotImplementedError: Could not find signature for dtype: <OracleDialect_cx_oracle, INTERVAL>
```

The reported problem is for `validate schema`, we should also test `column` and `row` to understand what is required there.

### PR DESCRIPTION
**Pull request by nj1973**
This PR fixes an exception when validating an Oracle table containing an INTERVAL DAY TO SECOND column.

It also adds the column to the `dvt_ora2pg_types` test table.

It does not:

1. Does not enable INTERVAL YEAR TO MONTH. This data type is not supported at all by cx-Oracle and therefore needs a different approach
2. Does not fix row or column validation. This is a bigger, not Oracle specific issue: https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1214

### CODE REVIEW

**Comment by helensilva14** [comment]
> Does not enable INTERVAL YEAR TO MONTH. This data type is not supported at all by cx-Oracle and therefore needs a different approach

Regarding this observation: does the customer have columns with this other data type at the moment?

**Review by helensilva14 — APPROVED** [review]
LGTM!

**Comment by nj1973** [comment]
> > Does not enable INTERVAL YEAR TO MONTH. This data type is not supported at all by cx-Oracle and therefore needs a different approach
> 
> Regarding this observation: does the customer have columns with this other data type at the moment?

Not that they have shared with me. They have 100s of databases though so it would not surprise me if it came up. As I said above though, the solution will be different so I don't think it should be connected to this fix.

**Pull request merged**
