### PR TITLE
chore: remove support run command

### LINKED ISSUE #503: Remove support for 'data validation run' command
We have deprecated support for `data validation run --type column` syntax for versions >1.3.2 in support of `data-validation validate column/schema/row/custom-query` command. 

We should clean up the code to remove support for the 'run' option when validating through the CLI.

### PR DESCRIPTION
**Pull request by mloeberc**
changes to cli_tools.py file to remove suppoprt for run command.
Closes #503

### CODE REVIEW

**Review by nehanene15 — CHANGES_REQUESTED** [review]
There is still a some downstream references that need to be deleted/updated like so - https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/data_validation/__main__.py#L500 

And here: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/e3d42cc9a1dea092d15687e9995fa41f18f59aeb/data_validation/__main__.py#L203. We reference args.type which was only supported with the deprecated `data-validation run --type column`

**Comment by mloeberc** [comment]
@nehanene15 Hi Neha, I made the changes and left the validations running. Lete me know if everything is ok now.

**Review by helensilva14 — APPROVED** [review]
LGTM!

**Review by nehanene15 — APPROVED** [review]

**Pull request merged**
