### PR TITLE
chore: Upgrade package versions

### LINKED ISSUE #1147: DVT and Airflow Providers Google Library Conflicts
Hello, 

We were looking at executing the Data Validation Tool from within the Composer as per instructions in https://github.com/GoogleCloudPlatform/professional-services-data-validator/tree/develop/samples/airflow. We are getting versions conflict  because DVT needs specific versions of Google Cloud Libraries which conflict with the versions needed by "apache-airflow-providers-google" (Links below). 

https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/210c352ae8a601833a6e34b13972145abc1d49a6/setup.py#L55 

https://github.com/apache/airflow/blob/482c0be434cf4cd6d4769634f859cb5e5a243e9d/airflow/providers/google/provider.yaml#L141

Could you please guide us on finding compatible versions for DVT and Airflow Providers Google that can work on a Cloud Composer version? Or if we are missing something.

Thanks,
Moiz

### PR DESCRIPTION
**Pull request by nehanene15**
Upgrade secret-manager to avoid conflicts with `apache-airflow-providers-google` when using Cloud Composer.

Closes #1147

### CODE REVIEW

**Comment by moizarafat** [comment]
@nehanene15 Thanks for the quick turn around. Could we also upgrade the versions for below to support >= same as apache-airflow-providers-google  ?

google-cloud-bigquery
google-cloud-bigquery-storage 
google-cloud-spanner
google-cloud-storage 
google-api-python-client

**Comment by nehanene15** [comment]
> @nehanene15 Thanks for the quick turn around. Could we also upgrade the versions for below to support >= same as apache-airflow-providers-google ?
> 
> google-cloud-bigquery google-cloud-bigquery-storage google-cloud-spanner google-cloud-storage google-api-python-client

Yes, I checked those packages as well and DVT should not conflict with those.

**Comment by helensilva14** [comment]
Fix #1091, #1092, #1140 - Merging will enable the closure for these other dependency-related PRs

**Comment by nehanene15** [comment]
Closing since this fix will be merged in #1150

**Pull request closed without merging**
