### PR TITLE
feat: Add more mappings to the allowlist configuration file oracle_to_bigquery.yaml

### PR DESCRIPTION
**Pull request by helensilva14**
Mappings identified when performing new tests for Oracle to BQ validations.

### CODE REVIEW

**Comment by nj1973** [comment]
I've tweaked the additions but this has highlighted a code issue we need to resolve. The decimal precision/scale expansion doesn't work for not-null columns since we added the `!` marker for not null.
I've also added a unit test to prove this isn't working.
I'll add a fix for it today.

**Review by nj1973 — APPROVED** [review]
LGTM

**Comment by helensilva14** [comment]
Thanks a lot Neil!

**Pull request merged**
