### PR TITLE
Fix: Update README.md

### PR DESCRIPTION
**Pull request by ebartels**
Adjust formatting to use bulleted list.

### CODE REVIEW

**Comment by dhercher** [comment]
Hi Erik, thanks for the contribution!  No no to clean the formatting, if you could sign the CLA than I would be very happy to accept the PR!

**Comment by nehanene15** [comment]
@ebartels Thank you for your PR. The underlying README has been updated leading to merge conflicts. Could this PR please be updated or closed depending on what changes you would like to make?

**Comment by ebartels** [comment]
> @ebartels Thank you for your PR. The underlying README has been updated leading to merge conflicts. Could this PR please be updated or closed depending on what changes you would like to make?

It looks like you have rolled in these changes [here](https://github.com/GoogleCloudPlatform/professional-services-data-validator/commit/fc73e21810ffe74459a90b79b956a91168c0dc1c) so I will close this PR.  

In the future I'll sign the CLA as well. 

Thanks

**Pull request closed without merging**
