### PR TITLE
fix: Fix issue where long rows were being truncated in raw query command

### LINKED ISSUE #1361: data-validation query output truncated for long strings
Test case:
```
Q="SELECT RPAD('some-long-string',128,'x') c FROM dual
UNION ALL
SELECT RPAD('some-long-string',256,'y') c FROM dual
UNION ALL
SELECT RPAD('some-long-string',384,'z') c FROM dual
"

data-validation query --conn ora_local --query="${Q}"
```

Output, notice the `... (86 characters truncated) ...` section in the text below:
```
[('some-long-stringxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',),
 ('some-long-stringyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',),
 ('some-long-stringzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz ... (86 characters truncated) ... zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',)]
```

### PR DESCRIPTION
**Pull request by nj1973**
For long strings output by `data-validation query` commands we were losing detail, notice the ... (86 characters truncated) ... section in the text below:
```
[('some-long-stringxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',),
 ('some-long-stringyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',),
 ('some-long-stringzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz ... (86 characters truncated) ... zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz',)]
```

This PR:

- Prevents the truncation by converting SQLAlchemy Row() objects to a tuple before letting Python implicitly call `str()` or `repr()`.
- Adds tests for `data-validation query` seeing as we didn't have any.

### CODE REVIEW

**Review by helensilva14 — APPROVED** [review]
LGTM, well done!

**Comment by sundar-mudupalli-work** [comment]
Thank you.

**Review by sundar-mudupalli-work — APPROVED** [review]
LGTM

**Pull request merged**
