### PR TITLE
docs: fix typo on ibis_snowflake

### PR DESCRIPTION
**Pull request by jmg-duarte**
I'm assuming the Snowflake file shouldn't be referencing Oracle Exadata

### CODE REVIEW

**Comment by nehanene15** [comment]
Could you merge the latest develop branch? The tests are failing due to an older version of the black linter (black==19.10b0) that we have upgraded.

**Comment by jmg-duarte** [comment]
@nehanene15 done, please review. Thank you!

**Review by helensilva14 — APPROVED** [review]
Tests are passing now! Thanks for your contribution @jmg-duarte :)

**Pull request merged**
