### PR TITLE
feat: Support row validation of boolean columns

### LINKED ISSUE #1262: Error while validating Postgres BOOLEAN datatype with Teradata CHAR datatype in row validation
Customer facing another issue while validating Postgres with Teradata. They've a column,ISCURRENTFORTYPE, defined boolean in Postgres and CHAR(1) in Teradata. When they're validating this column using comp field comparison using below command, it's throwing error : 

data-validation validate row \
--source-conn pg_conn \
--target-conn td_conn \
--tables-list public.eodassetlocation=Z_OD_ALF_LIVE_M_Q.Z0325_ODSASSETLOC_CURR \
-tsp \
--primary-keys ID \
--comparison-fields ID,ASSETID,ISCURRENTFORTYPE \
--bq-result-handler prj-dfdl-528-fcmis-d-528.bq_dvt_validation_results_raw.bq_postgres_td_dvt_validation_results \
-l Tables=public.eodassetlocation:Z_OD_ALF_LIVE_M_Q.Z0325_ODSASSETLOC_CURR,run_date=20240910-1

**Error :** 
ibis.common.exceptions.IbisTypeError: Given arguement with datatype boolean is not implicitly castable to string.

Later they created a view on TD to type cast column ISCURRENTFORTYPE to BYTEINT and used view in DVT validation. Got below error : 

**TypeError:** Arguments differences_target_value:int64 and differences_source_value:boolean are not comparable

### LINKED ISSUE #1279: Boolean data type support
Not all systems have a boolean data type. When comparing systems that do with systems that don't the incompatible data types can prove a problem. Using Oracle (no boolean type) vs PostgreSQL (has a boolean type) as an example.

**Test table**

Oracle:
```
create table dvt_test.tab_bool
( id number(5)
, col_bool_dec number(1)
, col_bool_int number(1)
, col_bool_ch1 char(1)
, col_bool_chy char(1));
insert into dvt_test.tab_bool values (1,1,1,'1','Y');
insert into dvt_test.tab_bool values (2,0,0,'0','N');
commit;
```

PostgreSQL:
```
create table dvt_test.tab_bool
( id int
, col_bool_dec boolean
, col_bool_int boolean
, col_bool_ch1 boolean
, col_bool_chy boolean);
insert into dvt_test.tab_bool values (1,true,true,true,true);
insert into dvt_test.tab_bool values (2,false,false,false,false);
```

**Column validation**
```
data-validation validate column --source-conn ora --target-conn pg \
--tables-list "dvt_test.tab_bool" --count="*"
...
  File "/usr/local/google/home/neiljohnson/github/professional-services-data-validator/.venv/lib/python3.11/site-packages/ibis/expr/rules.py", line 270, in value
    raise com.IbisTypeError(
ibis.common.exceptions.IbisTypeError: Given argument with datatype boolean is not implicitly castable to string
```

**Row validation**

No exceptions but column contents are incompatible:
```
data-validation validate row --source-conn ora --target-conn pg \
--tables-list "dvt_test.tab_bool" --primary-keys id --concat="*"

╤══════════════════════╤════════════════════╤═══════════════════════╤══════════════════╤═════════════════════╤
│ source_column_name   │ source_agg_value   │ target_agg_value      │ pct_difference   │ validation_status   │
╪══════════════════════╪════════════════════╪═══════════════════════╪══════════════════╪═════════════════════╪
│ concat__all          │ 1111Y              │ 1truetruetruetrue     │                  │ fail                │
┼──────────────────────┼────────────────────┼───────────────────────┼──────────────────┼─────────────────────┼
│ concat__all          │ 2000N              │ 2falsefalsefalsefalse │                  │ fail                │
╧══════════════════════╧════════════════════╧═══════════════════════╧══════════════════╧═════════════════════╧
```

### PR DESCRIPTION
**Pull request by nj1973**
This PR merges the following changes:

- Adds support for boolean data types
- Adds support for validating numeric or string columns against a boolean column (more below)
- Adds a new integration test table dvt_bool

Validating numeric or string columns against boolean columns. Some engines, such as Oracle & Teradata, do not have a boolean data type. In these systems it is typical to either use numeric 1 and 0 for string 1/Y and 0/N for True and False. 

**Hash/concat validation**
When non-boolean columns are validated against boolean columns we look for values like above and use a case statement to convert them to a string "true" or "false". I believe the code I've added is not engine specific so if I missed a system, such as DB2, then I expect the code will work anyway.

**Comparison fields**
When non-boolean columns are validated against boolean columns I translate them to numeric 1 or 0. This doesn't look the same as True or False but Pandas is able to compare them and give a success/fail status correctly.

I've added the usual tests for schema validation and row validation. No tests for column validation because this data type is skipped for aggregations.

### CODE REVIEW

**Review by helensilva14 — APPROVED** [review]
LGTM! Impeccable PR, very complete with all the specific tests, just amazed once again by your awesome work! 👏

**Comment by nj1973** [comment]
Can we add a comment to this section describing how we validate bool types: https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/develop/README.md#hash-concat-and-comparison-fields

Also the UPPER statement is probably not true.

**Pull request merged**
