### PR TITLE
fix: get_schema with Postgres

### PR DESCRIPTION
**Pull request by FX-HAO**
#410

### CODE REVIEW

**Review by dhercher — CHANGES_REQUESTED** [review]
Code looks good.  It would be great to add an integration test to either MySQL or PSQL to validate this PR.  Also to BigQuery or a different source which should not be affected to ensure no gression

**Comment by FX-HAO** [comment]
@dhercher added tests for MySQL and PG. There are already schema validations for other sources, see https://github.com/GoogleCloudPlatform/professional-services-data-validator/blob/783cdf8810c29755b26e4894555b6dd03f4c9025/tests/system/data_sources/test_bigquery.py#L252-L257

**Comment by FX-HAO** [comment]
don't know why the CI failed, both of tests succeeded on my local. and cannot get the error details

**Comment by dhercher** [comment]
> don't know why the CI failed, both of tests succeeded on my local. and cannot get the error details

```
Traceback (most recent call last):
  File "/workspace/.nox/lint/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/workspace/.nox/lint/lib/python3.9/site-packages/black.py", line 4134, in patched_main
    patch_click()
  File "/workspace/.nox/lint/lib/python3.9/site-packages/black.py", line 4123, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/workspace/.nox/lint/lib/python3.9/site-packages/click/__init__.py)
```

**Comment by nehanene15** [comment]
> don't know why the CI failed, both of tests succeeded on my local. and cannot get the error details

This was an issue with a package being used in our Cloud Build tests. Please pull and merge the [latest code](https://github.com/GoogleCloudPlatform/professional-services-data-validator/pull/413) from develop to resolve this.

**Comment by FX-HAO** [comment]
@nehanene15 updated with the latest code. please rerun the tests

**Comment by dhercher** [comment]
We've been cleaning some dependency issues which cropped up.  I'm going to try tests but likely you will need to merge develop again

**Comment by FX-HAO** [comment]
updated

**Review by dhercher — APPROVED** [review]

**Pull request merged**
